#!/bin/bash
# RC grid sync — generated by scheduled task rc-grid-sync (2026-06-11)
# Pushes Rating Captain grid positions (latest scan: 2026-06-10) to project 3 (Car Key Rescue Perth)
curl -sS -X POST "https://seo-room-v5-production.up.railway.app/api/projects/3/rc-grid-sync" -H "Content-Type: application/json" --data @"$(dirname "$0")/rc_sync_payload.json"
